cargo-features = ["edition"]

[package]
name = "glad-wrap"
version = "0.1.0"
authors = ["Scott Moore <scott.will.moore@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10"
glutin = "0.18"
image = "0.19"
nalgebra = "0.16"